# .github/workflows/secops.yml
name: SecOps/Global Deployment
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'environments/secops/**'
      - 'global/**'

jobs:
  deploy-secops:
    runs-on: ubuntu-latest
    environment: secops
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      # === DEPLOY SECOPS RESOURCES ===
      - name: Assume SecOps Role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::993490993886:role/GitHubActions-SecOps-Deployer
          aws-region: us-east-1
          role-session-name: GitHubActions-SecOps

      - name: Terraform Init (SecOps)
        run: terraform init
        working-directory: environments/secops

      - name: Terraform Plan (SecOps)
        run: terraform plan -out=tfplan.secops
        working-directory: environments/secops

      - name: Terraform Apply (SecOps)
        run: terraform apply -auto-approve tfplan.secops
        working-directory: environments/secops

      # === DEPLOY SCPs IN MANAGEMENT ACCOUNT ===
      - name: Assume Management Role for SCPs
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::783330585630:role/GitHubActions-SCP-Deployer
          aws-region: us-east-1
          role-session-name: GitHubActions-Management-SCPs

      - name: Terraform Init (SCPs)
        run: terraform init
        working-directory: global

      - name: Terraform Plan (SCPs)
        run: terraform plan -out=tfplan.scps
        working-directory: global

      - name: Terraform Apply (SCPs)
        run: terraform apply -auto-approve tfplan.scps
        working-directory: global

      # === FINAL VERIFICATION ===
      # Re-assume SecOps role before verifying SecOps backend
      - name: Verify SecOps Deployment
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::993490993886:role/GitHubActions-SecOps-Deployer
          aws-region: us-east-1
          role-session-name: GitHubActions-SecOps-Verify

      - name: Terraform Plan (SecOps Verification)
        run: terraform plan
        working-directory: environments/secops

      # Re-assume SCP/Management role before verifying SCPs backend
      - name: Verify SCPs Deployment
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::783330585630:role/GitHubActions-SCP-Deployer
          aws-region: us-east-1
          role-session-name: GitHubActions-Management-SCPs-Verify

      - name: Terraform Plan (SCPs Verification)
        run: terraform plan
        working-directory: global
