name: Security Check

on:
  push:
    branches: [main]
  pull_request:

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.5.0"

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        run: terraform validate -no-color

      - name: Run Checkov Scan
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: .
          framework: terraform
          quiet: true
          soft_fail: false
          download_external_modules: true
          skip_check: ""
          output_format: sarif
          output_file_path: checkov-results.sarif
          check: |
            CKV_AWS*
            CKV_CIS*
            CKV2_AWS*
            CKV2_CIS*

      - name: Upload Security Report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: checkov-results-${{ github.run_id }}.sarif
          category: checkov-${{ github.run_id }}