name: Terraform CI - Dev

on:
  push:
    branches:
      - main          # only trigger on oidc-test branch
    paths:
      - 'environments/dev/**'
  pull_request:
    branches:
      - main          # also run on PRs into oidc-test
    paths:
      - 'environments/dev/**'
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: dev
    defaults:
      run:
        working-directory: environments/dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials with OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::961535847135:role/perp-dev-github-actions-role
          aws-region: us-east-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan